### ISSUE TITLE
USER:  auth and identification.

### ISSUE THREAD

**Issue by seitbekir** [seitbekir/sockrest#1]
After connection user might be identified. Auth logic have to be in special function, that fires after connect and reconnect. User data has to be stored in connection.

User may be identified by an ID, and working with user has to be encapsulated.

user auth:
```js
app.user('user-connected', connection => {
    // connection is socket connection instance
    // connection.data contains queried creds
    let data = connection.data
    if ('id' in data) {
        db.findUserById(data.id)
            .then(res => {
                connection.setUser(data.id, res)
                // Client got message, that connection is allowed
                connection.allow()
            })
            .catch(err => {
                // Client got message, that connection is denied by server
                connection.deny({
                    message: 'this ID not allowed to be authorized'
                })
            })
    }
})
```

## Roadmap

- [x] Support token getting
- [x] Support user events
- [x] Create User prototype
- [x] Support user object to keep connections
- [ ] Make User class to work with connection
- [ ] Add events support 
    - [ ] first-connected
    - [ ] new-connected
    - [ ] last-connected
    - [ ] user-disconnected
